# Generated by Django 4.2.7 on 2026-01-16 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('study_sessions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmotionalStateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('energy_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Physical/mental energy level', max_length=10)),
                ('stress_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Study-related stress level', max_length=10)),
                ('focus_level', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], help_text='Ability to concentrate', max_length=10)),
                ('source', models.CharField(choices=[('self_report', 'Self-Reported'), ('inferred', 'Inferred from Behavior')], help_text='How this state was captured', max_length=20)),
                ('trigger_context', models.CharField(blank=True, help_text='What triggered this log (e.g., session_end, day_start)', max_length=100)),
                ('study_session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emotional_logs', to='study_sessions.studysession')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emotional_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Emotional State Log',
                'verbose_name_plural': 'Emotional State Logs',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user', '-timestamp'], name='emotional_s_user_id_35a0d5_idx'), models.Index(fields=['source', '-timestamp'], name='emotional_s_source_edd06f_idx')],
            },
        ),
    ]
