# Generated by Django 4.2.7 on 2026-01-16 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PlanAdjustmentSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('triggered_by', models.CharField(help_text='What triggered this suggestion (e.g., high_stress, at_risk, overrun)', max_length=100)),
                ('triggered_at', models.DateTimeField(auto_now_add=True)),
                ('context', models.JSONField(help_text='Context: emotional_state, dominant_error_topic, etc.')),
                ('adjustments', models.JSONField(help_text='List of suggested adjustments with details')),
                ('rationale', models.TextField(help_text='AI explanation for these suggestions (MANDATORY)')),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('user_notes', models.TextField(blank=True, help_text='User notes on why they accepted/rejected')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_suggestions', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='adjustment_suggestions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Plan Adjustment Suggestion',
                'verbose_name_plural': 'Plan Adjustment Suggestions',
                'ordering': ['-triggered_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('uploaded_file', models.FileField(blank=True, help_text='PDF file of diagnostic test (optional)', null=True, upload_to='diagnostics/')),
                ('analysis_result', models.JSONField(blank=True, help_text='AI analysis result: {"error_groups": [...]}', null=True)),
                ('analyzed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_test', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='diagnostic_tests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Diagnostic Test',
                'verbose_name_plural': 'Diagnostic Tests',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DiagnosticQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_number', models.IntegerField(help_text='Question number in the test')),
                ('question_text', models.TextField()),
                ('correct_answer', models.TextField()),
                ('user_answer', models.TextField()),
                ('topic', models.CharField(blank=True, help_text='Subject topic (optional)', max_length=200)),
                ('is_correct', models.BooleanField(default=False)),
                ('error_type', models.CharField(blank=True, choices=[('conceptual', 'Conceptual Error'), ('application', 'Application Error'), ('reasoning', 'Reasoning Error')], help_text='Type of error if answer is incorrect', max_length=20)),
                ('diagnostic_test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='diagnostics.diagnostictest')),
            ],
            options={
                'verbose_name': 'Diagnostic Question',
                'verbose_name_plural': 'Diagnostic Questions',
                'ordering': ['question_number'],
                'unique_together': {('diagnostic_test', 'question_number')},
            },
        ),
    ]
