"""
JSON schemas for AI outputs

All AI responses must conform to these strict schemas to ensure
predictable, structured output that can be safely processed.
"""
from typing import TypedDict, Literal, List, Optional


# Task types allowed in the system
TaskType = Literal["concept_review", "practice", "deep_practice", "revision", "mock_test"]

# Difficulty levels
DifficultyLevel = Literal["low", "medium", "high"]

# Cognitive load levels
CognitiveLoad = Literal["low", "medium", "high"]


class LearningTask(TypedDict):
    """
    Schema for a single learning task generated by AI.

    Constraints:
    - suggested_duration_minutes: Must be between 25-60 minutes
    - Tasks must be independent and reorderable
    - No task dependencies allowed
    """
    title: str
    task_type: TaskType
    suggested_duration_minutes: int  # 25-60 only
    difficulty: DifficultyLevel
    cognitive_load: CognitiveLoad
    notes: Optional[str]


class LearningPlan(TypedDict):
    """
    Schema for complete learning plan output from AI.

    This is returned from AI Use Case #1: Event → Learning Plan Generation
    """
    goal_summary: str
    tasks: List[LearningTask]


class TaskSplitSuggestion(TypedDict):
    """
    Suggestion to split a task into smaller units.
    """
    action: Literal["split_task"]
    task_title: str
    new_duration_minutes: int


class ReplanSuggestion(TypedDict):
    """
    Schema for adaptive re-planning suggestions.

    This is returned from AI Use Case #3: Adaptive Re-Planning
    """
    issue_detected: Literal["tasks_overrunning", "tasks_skipped", "event_at_risk"]
    suggestions: List[TaskSplitSuggestion]


def validate_learning_task(task: dict) -> bool:
    """
    Validate a learning task matches the schema.

    Args:
        task: Dictionary containing task data

    Returns:
        True if valid, raises ValueError otherwise
    """
    required_fields = ["title", "task_type", "suggested_duration_minutes",
                      "difficulty", "cognitive_load"]

    # Check required fields
    for field in required_fields:
        if field not in task:
            raise ValueError(f"Missing required field: {field}")

    # Validate task_type
    valid_task_types = ["concept_review", "practice", "deep_practice", "revision", "mock_test"]
    if task["task_type"] not in valid_task_types:
        raise ValueError(f"Invalid task_type: {task['task_type']}")

    # Validate duration (25-60 minutes)
    duration = task["suggested_duration_minutes"]
    if not isinstance(duration, int) or duration < 25 or duration > 60:
        raise ValueError(f"Duration must be 25-60 minutes, got: {duration}")

    # Validate difficulty
    valid_levels = ["low", "medium", "high"]
    if task["difficulty"] not in valid_levels:
        raise ValueError(f"Invalid difficulty: {task['difficulty']}")

    # Validate cognitive_load
    if task["cognitive_load"] not in valid_levels:
        raise ValueError(f"Invalid cognitive_load: {task['cognitive_load']}")

    return True


def validate_learning_plan(plan: dict) -> bool:
    """
    Validate a complete learning plan matches the schema.

    Args:
        plan: Dictionary containing learning plan data

    Returns:
        True if valid, raises ValueError otherwise
    """
    if "goal_summary" not in plan:
        raise ValueError("Missing goal_summary")

    if "tasks" not in plan or not isinstance(plan["tasks"], list):
        raise ValueError("Missing or invalid tasks list")

    if len(plan["tasks"]) == 0:
        raise ValueError("Learning plan must contain at least one task")

    # Validate each task
    for i, task in enumerate(plan["tasks"]):
        try:
            validate_learning_task(task)
        except ValueError as e:
            raise ValueError(f"Task {i} validation failed: {str(e)}")

    return True
